

export const YFWImageConst = {
    //公共资源
    Bg_search_empty:require('../../../img/ic_no_goods_shops.png'),
    Bg_address_empty:require('../../../img/ic_no_address.png'),
    Bg_collection_empty:require('../../../img/ic_no_collection.png'),
    Bg_label_package:require('../../../img/Label_taocan.png'),
    Bg_label_package_treatment:require('../../../img/Label_liaocheng.png'),
    Bg_order_detail_color_line:require('../../../img/order_detail_color_line.png'),

    Icon_unChooseBtn:require('../../../img/check_discheck.png'),
    Icon_address: require('../../../img/order_detail_location.png'),
    Icon_no_pic:require('../../../img/nopic.png'),
    Icon_default_pic:require('../../../img/default_img.png'),
    Icon_warning:require('../../../img/icon_warning.png'),
    Icon_confirm:require('../../../img/sx_icon_baozhang.png'),
    Icon_message_next:require('../../../img/message_next.png'),
    Icon_status_icon_success:require('../../../img/order_status_icon_success.png'),
    Icon_status_icon_failed:require('../../../img/order_status_icon_failed.png'),
    Icon_status_icon_return:require('../../../img/order_status_icon_return.png'),
    Icon_status_icon_wait:require('../../../img/order_status_icon_wait.png'),
    Icon_order_detail_service:require('../../../img/order_detail_service.png'),
    Icon_order_detail_store_phone:require('../../../img/order_detail_store_phone.png'),
    Icon_order_tips_clear_icon:require('../../../img/ordertips_clear_icon.png'),
    Icon_warning_complain:require('../../../img/icon_warning_compaliant.png'),
    Icon_gary_wenhao:require('../../../img/icon_gary_wenhao.png'),
    Icon_del_pic:require('../../../img/ic_pic_del.png'),
    Icon_share_wx:require('../../../img/share_0.png'),
    Icon_share_qq:require('../../../img/share_3.png'),
    Icon_share_sms:require('../../../img/icon_sms.png'),
    Icon_coupon:require('./icon_coupon.png'),

    Btn_input_del:require('./btn_input_del.png'),
    Btn_qr_scan:require('./btn_qr_scan.png'),
    Btn_bar_search:require('./btn_bar_search.png'),
    More_arrow_right:require('./arrow_right.png'),
    Icon_close:require('./icon_close.png'),
    Icon_store:require('./icon_store.png'),
    Icon_shop_cart:require('./icon_shop_cart.png'),
    Icon_arrow_down:require('./icon_arrow_down.png'),
    Icon_ashcan:require('./icon_ashcan.png'),
    Bg_page_header:require('./bg_page_header.png'),
    Bg_page_header_h:require('./bg_page_header_h.png'),

    Tab_home_normal:require('./tab_home_normal.png'),
    Tab_home_select:require('./tab_home_selected.png'),
    Tab_shopcar_normal:require('./tab_shopcar_normal.png'),
    Tab_shopcar_select:require('./tab_shopcar_selected.png'),
    Tab_mine_normal:require('./tab_mine_normal.png'),
    Tab_mine_select:require('./tab_mine_selected.png'),

    Nav_back_white:require('./top_back_white.png'),
    Nav_header_background_blue: require('./status_bar_blue.png'),


    Order_icon_dfk:require('./order_icon_dfk.png'),
    Order_icon_dpj:require('./order_icon_dpj.png'),
    Order_icon_dsh:require('./order_icon_dsh.png'),
    Order_icon_thk:require('./order_icon_thk.png'),
    Order_icon_dfh:require('./order_icon_dfh.png'),

    Setting_icon_yhq:require('./user_icon_yhq.png'),
    Setting_icon_kpxx:require('./user_icon_kpxx.png'),
    Setting_icon_rjsz:require('./user_icon_rjsz.png'),
    Setting_icon_shdz:require('./user_icon_shdz.png'),
    Setting_icon_wdda:require('./user_icon_wdda.png'),
    Setting_icon_wdpj:require('./user_icon_wdpj.png'),
    Setting_icon_wdts:require('./user_icon_wdts.png'),
    Setting_icon_yqrz:require('./user_icon_yqrz.png'),

    Share_default:require('./share_default.png'),
    Share_goods:require('./goods_detail_share.png'),
    Share_shop:require('./shop_menu_share.png'),

    Market_icon_tip:require('./market_tip.png'),
    Market_icon_voice:require('./market_voice.png'),
    Market_icon_user:require('./market_user.png'),

    Icon_sell_data_p:require('./icon_sell_data_p.png'),

    List_order_by_default:require('./order_by_default.png'),
    List_order_by_desc:require('./order_by_desc.png'),
    List_icon_add_cart:require('./icon_add_cart.png'),
    List_icon_filter:require('./icon_filter.png'),
    Tag_bg_ticket:require('./tag_ticket.png'),
    Icon_select_blue:require('./icon_select_blue.png'),
    Icon_shop_kuang: require('./icon_shop_all_kuang.png'),

    Icon_list:require('./medicine_list_gray.png'),
    Icon_map:require('./medicine_map_gray.png'),
    List_drop_down:require('./drop_down_gray.png'),
    Btn_bar_search_gray:require('./top_bar_search.png'),

    Bg_success:require('./sucees_bg.png'),
    Icon_wallet:require('./icon_wallet.png'),
    Icon_price:require('./icon_price.png'),
    Icon_licence: require('./icon_licence.png'),

    Icon_address_blue: require('./icon_address_blue.png'),
    Icon_settle_address_bg: require('./icon_settle_address_bg.png'),

    Icon_next_orange: require('./icon_next_orange.png'),
    Icon_add_pic: require('./Icon_add_pic.png'),

    Icon_shop_auth:require('./icon_auth.png'),
    Icon_shop_no_auth: require('./icon_no_auth.png'),
    Icon_upload_photo:require('./icon_upload_pic.jpg'),

    Icon_tip:require('./icon_tip.png'),
    Icon_progress_on: require('./icon_check_progress_on.png'),

    Icon_order_message:require('./icon_order_message.png'),
    Icon_service_message:require('./icon_service_message.png'),
    Icon_system_message:require('./icon_system_message.png'),
    Icon_yh_message:require('./icon_yh_message.png'),
    Icon_nextroung_message:require('./icon_next_message.png'),
    Icon_no_message: require('./ic_no_message.png'),

    Icon_notice_2: require('./icon_notice_2.png'),
    Icon_notice: require('./icon_notice.png'),

    Bg_shop_bg_wd: require('./shop_bg_wd.png'),
    Icon_star_selected_red: require('./icon_star_selected_red.png'),
    Icon_star_selected_yellow: require('./icon_star_selected_yellow.png'),
    Icon_star_selected_gray: require('./icon_star_selected_gray.png'),
    Icon_gou_blue: require('./icon_gou_blue.png'),
    Icon_gou_hui: require('./icon_gou_hui.png'),
    Icon_title_bottom_line: require('./title_bottom_line.png'),
    Icon_add_idcard_background: require('./Icon_add_idcard_background.png'),
    Icon_add_idcard_front: require('./Icon_add_idcard_front.png'),
    Icon_add_pic_probate: require('./Icon_add_pic_probate.png'),
    Icon_more_white: require('./more_white.png'),
    Icon_empty_page: require('./empty_page.png'),

    Icon_wd_pop1: require('./wd_pop1.png'),
    Icon_wd_pop2: require('./wd_pop2.png'),
    Icon_wd_pop3: require('./wd_pop3.png'),
    Icon_wd_pop4: require('./wd_pop4.png'),
    Icon_wd_pop5: require('./wd_pop5.png'),

    Icon_coupon_bg: require('./coupon_bg.png'),
    Icon_coupon_open_bg: require('./coupon_open_bg.png'),
    Icon_coupon_used: require('./coupon_used.png'),
    Icon_coupon_overdue: require('./coupon_overdue.png'),
    Icon_coupon_willoverdue: require('./coupon_willoverdue.png'),
    Icon_icon_coupon_backimage: require('./icon_coupon_backimage.png'),
    Icon_icon_coupon_grayimage: require('./icon_coupon_grayimage.png'),
    Icon_icon_setup:require('./icon_setup.png'),

    image_guideArray_Doc_1: require('./guideArray_Doc_1.png'),
    image_guideArray_Doc_2: require('./guideArray_Doc_2.png'),
    image_guideArray_Doc_3: require('./guideArray_Doc_3.png'),
    image_guideArray_Doc_4: require('./guideArray_Doc_4.png'),

    image_guideArray_ID_1: require('./guideArray_ID_1.png'),
    image_guideArray_ID_2: require('./guideArray_ID_2.png'),

    Icon_single_store: require('./icon_single_store.png'),
    Icon_chain_store: require('./icon_chain_store.png'),
    Icon_blue_nike:require('./icon_blue_nike.png'),
    Icon_go_top:require('./icon_go_top.png'),
}
